apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-affinity
  name: node-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-affinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                values:
                - ssd
                operator: In
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
